### ISSUE TITLE
Post Batch Check Completion Issues

### ISSUE THREAD

**Issue by hayes042** [WholeFoodsCoop/Scannie#2]
ScannieV2.0 Batch Check is almost complete. The following issues exist:
- Scanner (SCS.php; scs.js) - After adding an item to a queue, the list of current queues is updated near the bottom of the screen. Currently, after this list is updated, the user cannot 'click' on a queue to remove it until the page is refreshed.
- Scanner: Editing Product User data - User cannot enter '&' and possibly many other 
- Review (BatchCheckQueues.php; batchCheckQueues,js; SCS.php) - If product locations are not set, they do not show up in the query / on the review page. Currently, the client would need to make sure there is a physical location entered for every product in the store before reviewing data.

**Comment by gohanman** [comment]
RE: `&`: that's probably HTTP/URI encoding where it gets interpreted as a field separator (`foo=1&bar=2`). Calling Javascript `encodeURIComponent()` on the string would fix it. Or JQuery like `$('#myform :input').serialize()` will grab all the form fields and escape values as needed.
